//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public int DealTypeId { get; set; }
        public int GenreId { get; set; }
        public int ConditionId { get; set; }
        public double IsActive { get; set; }
        public int UserId { get; set; }
    
        public virtual BookAuthor BookAuthor { get; set; }
        public virtual BookCondition BookCondition { get; set; }
        public virtual BookGenre BookGenre { get; set; }
        public virtual DealType DealType { get; set; }
        public virtual User User { get; set; }
    }
}
